name: 'build image'
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:
  # Build image once a week to apply updates in base image.
  schedule:
    - cron: 0 0 */7 * *
env:
  IMAGE_NAME: ${{github.repository}}
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v2
      - name: 'install buildx'
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: 'login to docker hub'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build $IMAGE_NAME
      run: |
        docker buildx build \
          --tag thedolt/$IMAGE_NAME:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .